#!/bin/bash

# If this check failed, see ptrip_lexer_state_hack.awk

function main
{
	pushd "$(dirname $(realpath $0))" > "/dev/null"
	
	local L_GET_VER="awk '/^# generated by lex-awk.awk/{print \$NF; exit(0)}'"
	diff <(eval $L_GET_VER ptrip_lexer.awk) <(eval $L_GET_VER ptrip_lexer_state_hack.awk)
	local L_DIFF_RES="$?"
	
	popd > "/dev/null"
	return "$L_DIFF_RES"
}

main
