#!/usr/bin/awk -f

# generated by smpg.awk 2.1

# <description>
function DESCRIPT_INCLUDES() {
return \
"included files:\n"\
"awklib_prog.awk\n"\
"awklib_tabs.awk\n"\
}
function DESCRIPT_FSM() {
return \
"fsm rules:\n"\
"start  -> prefix | defn\n"\
"prefix -> defn\n"\
"defn   -> field\n"\
"field  -> field | defn | end\n"\
"end    -> start\n"\
"\n"\
"'->' is read as 'must be followed by'\n"\
"'|' is read as 'or'"
}
function DESCRIPT() {
	return (DESCRIPT_INCLUDES() "\n" DESCRIPT_FSM())
}
# </description>

# <other>
# Author: Vladimir Dinev
# vld.dinev@gmail.com

function SCRIPT_NAME()    {return "tables.awk"}
function SCRIPT_VERSION() {return "1.0"}

# <awk_rules>
function init() {
	set_program_name(SCRIPT_NAME())

	if (Fsm)
		print_fsm()
	if (Help)
		print_help()
	if (Version)
		print_version()
	if (ARGC != 2)
		print_use_try()
}

function leave() {
	if (!should_skip_end()) {
		fsm_get_state(G_the_fsm)
		if (fsm_get_state(G_the_fsm) != FSM_END())
			fsm_on_error("", FSM_END(), fsm_get_state(G_the_fsm))
	}
}

BEGIN {
	init()
}

# ignore empty lines and comments
/^[[:space:]]*(#|$)/ {next}

# strip spaces and fsm
{
	gsub("^[[:space:]]+|[[:space:]]+$", "", $0)
	fsm_next(G_the_fsm, $1)
}

END {
	leave()
}
# </awk_rules>

function data_or_err() {
	if (NF < 2)
		error_qfpos(sprintf("no data after '%s'", $1))
}
function error_qfpos(msg) {
	error_quit(sprintf("file '%s' line %d: %s", FILENAME, FNR, msg))
}
# </other>

# <templated>
# 'prefix|defn|field'
function on_prefix(v) {prefix_save(v)}

function on_defn(v) {defn_save(v)}

function on_field(v) {field_save(v)}
# </templated>

# <fsm>
# <handlers>
function fsm_on_start() {
	prefix_save("tbl")
}
function fsm_on_prefix() {
	data_or_err()
	on_prefix($2)
}
function fsm_on_defn() {
	data_or_err()
	on_defn($2)
}
function fsm_on_field() {
	data_or_err()
	on_field($2)
}
function fsm_on_end() {
	generate()
	exit_success()
}
function fsm_on_error(curr_st, expected, got) {
	error_qfpos(sprintf("expected '%s', got '%s'", expected, got))
}
# </handlers>

# <constants>
function FSM_START() {return "start"}
function FSM_PREFIX() {return "prefix"}
function FSM_DEFN() {return "defn"}
function FSM_FIELD() {return "field"}
function FSM_END() {return "end"}
function _FSM_STATE() {return "state"}
# </constants>

# <functions>
function fsm_get_state(fsm) {return fsm[_FSM_STATE()]}
function _fsm_set_state(fsm, next_st) {fsm[_FSM_STATE()] = next_st}
function fsm_next(fsm, next_st,    _st) {

	_st = fsm_get_state(fsm)
	if ("" == _st) {
		if (FSM_START() == next_st)
		{fsm_on_start(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_START(), next_st)}
	}
	else if (FSM_START() == _st) {
		if (FSM_PREFIX() == next_st)
		{fsm_on_prefix(); _fsm_set_state(fsm, next_st)}
		else if (FSM_DEFN() == next_st)
		{fsm_on_defn(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_PREFIX()"|"FSM_DEFN(), next_st)}
	}
	else if (FSM_PREFIX() == _st) {
		if (FSM_DEFN() == next_st)
		{fsm_on_defn(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_DEFN(), next_st)}
	}
	else if (FSM_DEFN() == _st) {
		if (FSM_FIELD() == next_st)
		{fsm_on_field(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_FIELD(), next_st)}
	}
	else if (FSM_FIELD() == _st) {
		if (FSM_FIELD() == next_st)
		{fsm_on_field(); _fsm_set_state(fsm, next_st)}
		else if (FSM_DEFN() == next_st)
		{fsm_on_defn(); _fsm_set_state(fsm, next_st)}
		else if (FSM_END() == next_st)
		{fsm_on_end(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_FIELD()"|"FSM_DEFN()"|"FSM_END(), next_st)}
	}
	else if (FSM_END() == _st) {
		if (FSM_START() == next_st)
		{fsm_on_start(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_START(), next_st)}
	}
}
# </functions>
# </fsm>

# <includes>
# ../awklib/src/awklib_prog.awk
#@ <awklib_prog>
#@ Library: prog
#@ Description: Provides program name, error, and exit handling.
#@ Version 1.0
##
## Vladimir Dinev
## vld.dinev@gmail.com
## 2021-08-15
#@

#
#@ Description: Sets the program name to 'str'. This name can later be
#@ retrieved by get_program_name().
#@ Returns: Nothing.
#
function set_program_name(str) {

	_AWKLIB_prog__program_name = str
}

#
#@ Description: Provides the program name.
#@ Returns: The name as set by set_program_name().
#
function get_program_name() {

	return _AWKLIB_prog__program_name
}

#
#@ Description: Prints 'msg' to stderr.
#@ Returns: Nothing.
#
function pstderr(msg) {

	print msg > "/dev/stderr"
}

#
#@ Description: Sets a static flag which can later be checked by
#@ should_skip_end().
#@ Returns: Nothing.
#
function skip_end_set() {

	_AWKLIB_prog__skip_end_flag = 1
}

#
#@ Description: Clears the flag set by skip_end_set().
#@ Returns: Nothing.
#
function skip_end_clear() {

	_AWKLIB_prog__skip_end_flag = 0
}

#
#@ Description: Checks the static flag set by skip_end_set().
#@ Returns: 1 if the flag is set, 0 otherwise.
#
function should_skip_end() {

	return (_AWKLIB_prog__skip_end_flag+0)
}

#
#@ Description: Sets a static flag which can later be checked by
#@ did_error_happen().
#@ Returns: Nothing
#
function error_flag_set() {

	_AWKLIB_prog__error_flag = 1
}

#
#@ Description: Clears the flag set by error_flag_set().
#@ Returns: Nothing
#
function error_flag_clear() {

	_AWKLIB_prog__error_flag = 0
}

#
#@ Description: Checks the static flag set by error_flag_set().
#@ Returns: 1 if the flag is set, 0 otherwise.
#
function did_error_happen() {

	return (_AWKLIB_prog__error_flag+0)
}

#
#@ Description: Sets the skip end flag, exits with error code 0.
#@ Returns: Nothing.
#
function exit_success() {

	skip_end_set()
	exit(0)
}

#
#@ Description: Sets the skip end flag, exits with 'code', or 1 if 'code' is 0
#@ or not given.
#@ Returns: Nothing.
#
function exit_failure(code) {

	skip_end_set()
	exit((code+0) ? code : 1)
}

#
#@ Description: Prints '<program-name>: error: msg' to stderr. Sets the
#@ error and skip end flags.
#@ Returns: Nothing.
#
function error_print(msg) {

	pstderr(sprintf("%s: error: %s", get_program_name(), msg))
	error_flag_set()
	skip_end_set()
}

#
#@ Description: Calls error_print() and quits with failure.
#@ Returns: Nothing.
#
function error_quit(msg, code) {

	error_print(msg)
	exit_failure(code)
}
#@ </awklib_prog>
# ../awklib/src/awklib_tabs.awk
#@ <awklib_tabs>
#@ Library: tabs
#@ Description: String indentation.
#@ Version: 1.0
##
## Vladimir Dinev
## vld.dinev@gmail.com
## 2021-08-16
#@

#
#@ Description: Adds a tab to the indentation string.
#@ Returns: Nothing.
#
function tabs_inc() {

	++_AWKLIB_tabs__tabs_num
	_AWKLIB_tabs__tabs_str = (_AWKLIB_tabs__tabs_str "\t")
}

#
#@ Description: Removes a tab from the indentation string.
#@ Returns: Nothing.
#
function tabs_dec() {

	if (_AWKLIB_tabs__tabs_num) {
		--_AWKLIB_tabs__tabs_num
		_AWKLIB_tabs__tabs_str = substr(_AWKLIB_tabs__tabs_str, 1,
			_AWKLIB_tabs__tabs_num)
	}
}

#
#@ Description: Indicates the tab level.
#@ Returns: The number of tabs used for indentation.
#
function tabs_num() {

	return _AWKLIB_tabs__tabs_num
}

#
#@ Description: Provides all indentation tabs as a string.
#@ Returns: The indentation string.
#
function tabs_get() {

	return (_AWKLIB_tabs__tabs_str "")
}

#
#@ Description: Adds indentation to 'str'.
#@ Returns: 'str' prepended with the current number of tabs.
#
function tabs_indent(str) {

	return (_AWKLIB_tabs__tabs_str str)
}

#
#@ Description: Prints the indented 'str' to stdout without a new line
#@ at the end.
#@ Returns: Nothing.
#
function tabs_print_str(str) {

	printf("%s", tabs_indent(str))
}

#
#@ Description: Prints the indented 'str' to stdout with a new line at
#@ the end.
#@ Returns: Nothing.
#
function tabs_print(str) {

	print tabs_indent(str)
}
#@ </awklib_tabs>
# </includes>
# generated by tables.awk 1.0
#
# <tables-tables>
#
# prefix tables
#
# defn prefix
# field name
#
# defn defn
# field name
# field field[]
#
# defn field
# field name
# field is_arr
#
# <private>
function _tables_set(k, v) {__TABLES_tables_db__[k] = v}
function _tables_get(k) {return __TABLES_tables_db__[k]}
function _tables_set_count(k, c) {__TABLES_tables_db__[(k ".count")] = c}
function _tables_get_count(k) {return __TABLES_tables_db__[(k ".count")]}
function _tables_set_idx(k, i, v) {__TABLES_tables_db__[(k "." i)] = v}
function _tables_get_idx(k, i,    _x) {
	_x = (k "." i)
	if (_x in __TABLES_tables_db__)
		return __TABLES_tables_db__[_x]
	tables_errq(sprintf("entity '%s': not an index", _x))
}
function _tables_type_chk(ent, texp) {
	if (tables_type_of(ent) == texp)
		return
	tables_errq(sprintf("entity '%s': expected type match '%s', entity type '%s'",
		ent, texp, tables_type_of(ent)))
}
function _tables_new(type,    _ent) {
	_ent = _tables_get("ents")+1
	_tables_set("ents", _ent)
	_ent = ("_tables-" _tables_get("gen")+0 "-" _ent)
	_tables_set(_ent, type)
	return _ent
}
# <\private>

function tables_clear(    _gen) {
	_gen = _tables_get("gen")
	delete __TABLES_tables_db__
	_tables_set("gen", _gen+1)
}
function tables_is(ent) {return (ent in __TABLES_tables_db__)}
function tables_type_of(ent) {
	if (ent in __TABLES_tables_db__)
		return __TABLES_tables_db__[ent]
	tables_errq(sprintf("'%s' not an entity", ent))
}
# <defns>
# <type-prefix>
function TABLES_PREFIX() {return "prefix"}

function prefix_new(    _count, _id, _type) {
	_type = "prefix"
	_id = _tables_new(_type)
	_count = _tables_get_count(_type)+1
	_tables_set_count(_type, _count)
	_tables_set_idx(_type, _count, _id)
	return _id
}
function prefix_get(n) {return _tables_get_idx("prefix", n)}
function prefix_count() {return _tables_get_count("prefix")}
function prefix_last() {return prefix_get(prefix_count())}

function prefix_set_name(prefix_id, name) {
	_tables_type_chk(prefix_id, "prefix")
	_tables_set(("prefix." prefix_id ".name"), name)
}
function prefix_get_name(prefix_id) {
	_tables_type_chk(prefix_id, "prefix")
	return _tables_get(("prefix." prefix_id ".name"))
}
# <\type-prefix>
# <type-defn>
function TABLES_DEFN() {return "defn"}

function defn_new(    _count, _id, _type) {
	_type = "defn"
	_id = _tables_new(_type)
	_count = _tables_get_count(_type)+1
	_tables_set_count(_type, _count)
	_tables_set_idx(_type, _count, _id)
	return _id
}
function defn_get(n) {return _tables_get_idx("defn", n)}
function defn_count() {return _tables_get_count("defn")}
function defn_last() {return defn_get(defn_count())}

function defn_set_name(defn_id, name) {
	_tables_type_chk(defn_id, "defn")
	_tables_set(("defn." defn_id ".name"), name)
}
function defn_get_name(defn_id) {
	_tables_type_chk(defn_id, "defn")
	return _tables_get(("defn." defn_id ".name"))
}

function defn_add_field(defn_id, field,    _count, _n) {
	_tables_type_chk(defn_id, "defn")
	_n = ("defn." defn_id ".field")
	_count = _tables_get_count(_n)+1
	_tables_set_count(_n, _count)
	_tables_set_idx(_n, _count, field)
}
function defn_get_field(defn_id, n) {
	_tables_type_chk(defn_id, "defn")
	return _tables_get_idx(("defn." defn_id ".field"), n)
}
function defn_set_field(defn_id, n, field) {
	_tables_type_chk(defn_id, "defn")
	return _tables_set_idx(("defn." defn_id ".field"), n, field)
}
function defn_count_field(defn_id) {
	_tables_type_chk(defn_id, "defn")
	return _tables_get_count(("defn." defn_id ".field"))
}
function defn_last_field(defn_id) {
	return defn_get_field(defn_id, defn_count_field(defn_id))
}
# <\type-defn>
# <type-field>
function TABLES_FIELD() {return "field"}

function field_new(    _count, _id, _type) {
	_type = "field"
	_id = _tables_new(_type)
	_count = _tables_get_count(_type)+1
	_tables_set_count(_type, _count)
	_tables_set_idx(_type, _count, _id)
	return _id
}
function field_get(n) {return _tables_get_idx("field", n)}
function field_count() {return _tables_get_count("field")}
function field_last() {return field_get(field_count())}

function field_set_name(field_id, name) {
	_tables_type_chk(field_id, "field")
	_tables_set(("field." field_id ".name"), name)
}
function field_get_name(field_id) {
	_tables_type_chk(field_id, "field")
	return _tables_get(("field." field_id ".name"))
}

function field_set_is_arr(field_id, is_arr) {
	_tables_type_chk(field_id, "field")
	_tables_set(("field." field_id ".is_arr"), is_arr)
}
function field_get_is_arr(field_id) {
	_tables_type_chk(field_id, "field")
	return _tables_get(("field." field_id ".is_arr"))
}
# <\type-field>
# <\defns>
# <\tables-tables>
# <misc>
function is_name_arr(nm) {return (nm ~ /\[\]$/)}
function unarray(nm) {
	sub(/\[\]$/, "", nm)
	return nm
}
function nl() {print ""}

function tables_errq(msg) {
	error_quit(msg)
}
# </misc>

# <input>
function prefix_save(name,    _prefix_id) {
	_prefix_id = prefix_new()
	prefix_set_name(_prefix_id, name)
}

function prefix_name() {
	return prefix_get_name(prefix_last())
}

function defn_save(name,    _defn_id) {
	_defn_id = defn_new()
	defn_set_name(_defn_id, name)
}

function field_save(name,    _is_arr, _field_id) {
	if (_is_arr = is_name_arr(name))
		name = unarray(name)
	_field_id = field_new(name, _is_arr)
	field_set_name(_field_id, name)
	field_set_is_arr(_field_id, _is_arr)
	defn_add_field(defn_last(), _field_id)
}
# </input>

# <generate>
function tag_tables()   {return ("tables-" prefix_name())}
function tag_open(tag)  {print sprintf("# <%s>", tag)}
function tag_close(tag) {print sprintf("# <\\%s>", tag)}
function make_fnm(str)  {return (prefix_name() "_" str)}
function make_dbnm()    {return sprintf("__TABLES_%s_db__", prefix_name())}
function emit(str)      {tabs_print(str)}

function gen_base(    _fname, _db_nm) {
	tag_open("private")
	_db_nm = make_dbnm()

	_fname = ("_" make_fnm("set"))
	emit(sprintf("function %s(k, v) {%s[k] = v}", _fname, _db_nm))

	_fname = ("_" make_fnm("get"))
	emit(sprintf("function %s(k) {return %s[k]}", _fname, _db_nm))

	_fname = ("_" make_fnm("set_count"))
	emit(sprintf("function %s(k, c) {%s[(k \".count\")] = c}", _fname, _db_nm))

	_fname = ("_" make_fnm("get_count"))
	emit(sprintf("function %s(k) {return %s[(k \".count\")]}", _fname, _db_nm))

	_fname = ("_" make_fnm("set_idx"))
	emit(sprintf("function %s(k, i, v) {%s[(k \".\" i)] = v}", _fname, _db_nm))

	_fname = ("_" make_fnm("get_idx"))
	emit(sprintf("function %s(k, i,    _x) {", _fname))
	tabs_inc()
		emit("_x = (k \".\" i)")
		emit(sprintf("if (_x in %s)", _db_nm))
		tabs_inc()
			emit(sprintf("return %s[_x]", _db_nm))
		tabs_dec()
		emit(sprintf("%s_errq(sprintf(\"entity '%%s': not an index\", _x))",
				prefix_name()))
	tabs_dec()
	emit("}")

	#emit(sprintf("function %s(k, i) {return %s[(k \".\" i)]}", _fname, _db_nm))

	_fname = ("_" make_fnm("type_chk"))
	emit(sprintf("function %s(ent, texp) {", _fname))
	tabs_inc()
		emit(sprintf("if (%s(ent) == texp)", make_fnm("type_of")))
			tabs_inc()
			emit("return")
			tabs_dec()
		emit(                                                                 \
			sprintf(                                                          \
				(                                                             \
				"%s_errq(sprintf(\"entity '%%s': expected type match '%%s', " \
				"entity type '%%s'\",\n\t\tent, texp, %s(ent)))"              \
				),                                                            \
				prefix_name(),                                                 \
				make_fnm("type_of")                                           \
			)                                                                 \
		)
	tabs_dec()
	emit("}")
	_fname = ("_" make_fnm("new"))
	emit(sprintf("function %s(type,    _ent) {", _fname))
	tabs_inc()
		emit(sprintf("_ent = _%s(\"ents\")+1", make_fnm("get")))
		emit(sprintf("_%s(\"ents\", _ent)", make_fnm("set")))
		emit(                                                  \
			sprintf(                                           \
				"_ent = (\"_%s-\" _%s(\"gen\")+0 \"-\" _ent)", \
				prefix_name(),                                  \
				make_fnm("get")                                \
			)                                                  \
		)
		emit(sprintf("_%s(_ent, type)", make_fnm("set")))
		emit("return _ent")
	tabs_dec()
	emit("}")
	tag_close("private")

	nl()

	_fname = make_fnm("clear")
	emit(sprintf("function %s(    _gen) {", _fname))
	tabs_inc()
		emit(sprintf("_gen = _%s(\"gen\")", make_fnm("get")))
		emit(sprintf("delete %s", _db_nm))
		emit(sprintf("_%s(\"gen\", _gen+1)", make_fnm("set")))
	tabs_dec()
	emit("}")

	_fname = make_fnm("is")
	emit(sprintf("function %s(ent) {return (ent in %s)}", _fname, _db_nm))

	_fname = make_fnm("type_of")
	emit(sprintf("function %s(ent) {", _fname))
	tabs_inc()
		emit(sprintf("if (ent in %s)", _db_nm))
		tabs_inc()
			emit(sprintf("return %s[ent]", _db_nm, _db_nm))
		tabs_dec()
		emit(                                                     \
			sprintf(                                              \
				"%s_errq(sprintf(\"'%%s' not an entity\", ent))", \
				prefix_name()                                      \
			)                                                     \
		)
	tabs_dec()
	emit("}")
}

# <header>
function gen_defn_cmnts(    _i, _end, _defn_id) {
	_end = defn_count()
	for (_i = 1; _i <= _end; ++_i) {
		_defn_id = defn_get(_i)
		emit("#")
		emit(sprintf("# defn %s", defn_get_name(_defn_id)))
		gen_defn_field_cmnts(_defn_id)
	}
}
function gen_defn_field_cmnts(defn_id,    _i, _end, _str, _field_id) {
	_end = defn_count_field(defn_id)
	for (_i = 1; _i <= _end; ++_i) {
		_field_id = defn_get_field(defn_id, _i)
		_str = sprintf("# field %s", field_get_name(_field_id))
		if (field_get_is_arr(_field_id))
			_str = (_str "[]")
		emit(_str)
	}
}

function gen_header_cmnt() {
	emit(sprintf("# generated by %s %s", SCRIPT_NAME(), SCRIPT_VERSION()))
	emit("#")
}

function gen_struct_cmnts() {
	emit("#")
	emit(sprintf("# prefix %s", prefix_name()))
	gen_defn_cmnts()
	emit("#")
}
# </header>

function generate_field(defn_id, field_id,    _defn_nm, _field_nm) {
	_defn_nm  = defn_get_name(defn_id)
	_field_nm = field_get_name(field_id)

	if (field_get_is_arr(field_id)) {
		nl()
		emit(sprintf("function %s_add_%s(%s_id, %s,    _count, _n) {", _defn_nm,
			_field_nm, _defn_nm, _field_nm))
		tabs_inc()
			emit(sprintf("_%s(%s_id, \"%s\")", make_fnm("type_chk"), _defn_nm,
				_defn_nm))
			emit(sprintf("_n = (\"%s.\" %s_id \".%s\")", _defn_nm, _defn_nm,
				_field_nm))
			emit(sprintf("_count = _%s(_n)+1", make_fnm("get_count")))
			emit(sprintf("_%s(_n, _count)", make_fnm("set_count")))
			emit(sprintf("_%s(_n, _count, %s)", make_fnm("set_idx"), _field_nm))
		tabs_dec()
		emit("}")

		emit(sprintf("function %s_get_%s(%s_id, n) {", _defn_nm, _field_nm,
			_defn_nm))
		tabs_inc()
			emit(sprintf("_%s(%s_id, \"%s\")", make_fnm("type_chk"), _defn_nm,
				_defn_nm))
			emit(sprintf("return _%s((\"%s.\" %s_id \".%s\"), n)",
				make_fnm("get_idx"), _defn_nm, _defn_nm, _field_nm))
		tabs_dec()
		emit("}")

		emit(sprintf("function %s_set_%s(%s_id, n, %s) {", _defn_nm, _field_nm,
			_defn_nm, _field_nm))
		tabs_inc()
			emit(sprintf("_%s(%s_id, \"%s\")", make_fnm("type_chk"), _defn_nm,
				_defn_nm))
			emit(sprintf("return _%s((\"%s.\" %s_id \".%s\"), n, %s)",
				make_fnm("set_idx"), _defn_nm, _defn_nm, _field_nm, _field_nm))
		tabs_dec()
		emit("}")

		emit(sprintf("function %s_count_%s(%s_id) {", _defn_nm, _field_nm,
			_defn_nm))
		tabs_inc()
			emit(sprintf("_%s(%s_id, \"%s\")", make_fnm("type_chk"), _defn_nm,
				_defn_nm))
			emit(sprintf("return _%s((\"%s.\" %s_id \".%s\"))",
				make_fnm("get_count"), _defn_nm, _defn_nm, _field_nm))
		tabs_dec()
		emit("}")

		emit(sprintf("function %s_last_%s(%s_id) {", _defn_nm, _field_nm,
			_defn_nm))
		tabs_inc()
			emit(sprintf("return %s_get_%s(%s_id, %s_count_%s(%s_id))",
				_defn_nm, _field_nm, _defn_nm, _defn_nm, _field_nm, _defn_nm))
		tabs_dec()
		emit("}")
	} else {
		nl()
		emit(sprintf("function %s_set_%s(%s_id, %s) {", _defn_nm, _field_nm,
			_defn_nm, _field_nm))
		tabs_inc()
			emit(sprintf("_%s(%s_id, \"%s\")", make_fnm("type_chk"), _defn_nm,
				_defn_nm))
			emit(sprintf("_%s((\"%s.\" %s_id \".%s\"), %s)", make_fnm("set"),
				_defn_nm, _defn_nm, _field_nm, _field_nm))
		tabs_dec()
		emit("}")

		emit(sprintf("function %s_get_%s(%s_id) {", _defn_nm, _field_nm,
			_defn_nm))
		tabs_inc()
			emit(sprintf("_%s(%s_id, \"%s\")", make_fnm("type_chk"), _defn_nm,
				_defn_nm))
			emit(sprintf("return _%s((\"%s.\" %s_id \".%s\"))", make_fnm("get"),
				_defn_nm, _defn_nm, _field_nm))
		tabs_dec()
		emit("}")
	}
}

function generate_fields(defn_id,    _i, _end) {
	_end = defn_count_field(defn_id)
	for (_i = 1; _i <= _end; ++_i)
		generate_field(defn_id, defn_get_field(defn_id, _i))
}

function generate_defn(defn_id,    _name) {
	_name = defn_get_name(defn_id)

	tag_open(sprintf("type-%s", _name))
	emit(sprintf("function %s() {return \"%s\"}", toupper(make_fnm(_name)),
		_name))
	nl()

	emit(sprintf("function %s_new(    _count, _id, _type) {", _name))
	tabs_inc()
		emit(sprintf("_type = \"%s\"", _name))
		emit(sprintf("_id = _%s(_type)", make_fnm("new")))
		emit(sprintf("_count = _%s(_type)+1", make_fnm("get_count")))
		emit(sprintf("_%s(_type, _count)", make_fnm("set_count")))
		emit(sprintf("_%s(_type, _count, _id)", make_fnm("set_idx")))
		emit("return _id")
	tabs_dec()
	emit("}")

	emit(sprintf("function %s_get(n) {return _%s(\"%s\", n)}", _name,
		make_fnm("get_idx"), _name))

	emit(sprintf("function %s_count() {return _%s(\"%s\")}", _name,
		make_fnm("get_count"), _name))

	emit(sprintf("function %s_last() {return %s_get(%s_count())}", _name,
		_name, _name))

	generate_fields(defn_id)
	tag_close(sprintf("type-%s", _name))
}

function generate_defns(    _i, _end, _defn_id) {
	_end = defn_count()
	for (_i = 1; _i <= _end; ++_i)
		generate_defn(defn_get(_i))
}

function generate() {
	gen_header_cmnt()
	tag_open(tag_tables())
	gen_struct_cmnts()
	gen_base()
	tag_open("defns")
	generate_defns()
	tag_close("defns")
	tag_close(tag_tables())
}
# </generate>
# <doc>
function print_help() {
print sprintf("%s - data model compiler", SCRIPT_NAME())
print ""
print use_str()
print ""
print "Compiles data descriptions into a type system in awk. 'Compiles in awk'"
print "means it generates awk source code for setters/getters for each data's"
print "fields, along with functions to create a variable of a certain type of,"
print "data, check its type, and a db to remember the values of all fields."
print ""
print "E.g. the following describes the data model for this program itself:"
print ""
print "start"
print "prefix tables"
print ""
print "defn  prefix"
print "field name"
print ""
print "defn  defn"
print "field name"
print "field field[]"
print ""
print "defn  field"
print "field name"
print "field is_arr"
print "end"
print ""
print "The user must define an error function which the generated code can call."
print "With the provided example the function looks like: tables_errq(msg)"
print ""
print "To understand how this all works, it's best to look at the tables_*(),"
print "prefix_*(), defn_*(), and field_*(), functions in the source of this"
print "script."
print ""
print "Options:"
print "-vFsm=1     - print the fsm grammar"
print "-vVersion=1 - version information"
print "-vHelp=1    - this screen"
exit_success()
}
function print_fsm() {
	print DESCRIPT_FSM()
	exit_success()
}
function print_version() {
	print sprintf("%s %s", SCRIPT_NAME(), SCRIPT_VERSION())
	exit_success()
}
function use_str() {
	return sprintf("Use: %s <tables-file>", SCRIPT_NAME())
}
function print_use_try() {
	pstderr(use_str())
	pstderr(sprintf("Try: %s -vHelp=1", SCRIPT_NAME()))
	exit_failure()
}
# </doc>
