# <parse>
#
# translated by rdpg-to-awk.awk 2.2
# generated by rdpg-comp.awk 2.2.4
# 
# Immediate error detection: 0
# 
# Grammar:
# 
# 1. start : ptree_item_star TOK_EOI
# 
# 2. ptree_item : ptree_nl_star ptree_elem_opt \ptok_insert_ptree_delim PTOK_PTREE_DELIM
# 
# 3. ptree_item_star : ptree_item ptree_item_star
# 4. ptree_item_star : 0
# 
# 5. ptree_elem : ptree_tree
# 6. ptree_elem : ptree_include
# 
# 7. ptree_elem_opt : ptree_elem
# 8. ptree_elem_opt : 0
# 
# 9. ptree_tree : ptree_key ptree_val_opt ptree_nl_star ptree_subtree_opt
# 
# 10. ptree_key : ptree_wos \_ptree_on_key
# 
# 11. ptree_val : ptree_wos \_ptree_on_val
# 
# 12. ptree_val_opt : ptree_val
# 13. ptree_val_opt : 0
# 
# 14. ptree_subtree : TOK_L_CURLY \_ptree_lvl_push ptree_item_star TOK_R_CURLY \_ptree_lvl_pop
# 
# 15. ptree_subtree_opt : ptree_subtree
# 16. ptree_subtree_opt : 0
# 
# 17. ptree_include : TOK_INCLUDE ptree_string \_ptree_on_include
# 
# 18. ptree_wos : ptree_word
# 19. ptree_wos : ptree_string
# 
# 20. ptree_word : TOK_WORD \_ptree_read_word
# 
# 21. ptree_string : TOK_STRING \_ptree_read_string
# 
# 22. ptree_nl : TOK_NEW_LINE
# 
# 23. ptree_nl_star : ptree_nl ptree_nl_star
# 24. ptree_nl_star : 0
# 

# <public>
function rdpg_parse()
{
	if (!_RDPG_are_sets_init) {
		_rdpg_init_sets()
		_RDPG_are_sets_init = 1
	}
	_RDPG_had_error = 0
	return _rdpg_start() && !_RDPG_had_error
}
function rdpg_expect(arr_out,    _len) {
	delete arr_out
	if ("tok" == _RDPG_expect_type)
		arr_out[(_len = 1)] = _RDPG_expect_what
	else if ("set" == _RDPG_expect_type)
		_len = split(_RDPG_expect_sets[_RDPG_expect_what], arr_out, _RDPG_SEP())
	return _len
}
function rdpg_reread_curr_tok() {
	_RDPG_curr_tok = tok_curr()
}
function rdpg_state_get() {
	return ( \
	_RDPG_curr_tok    _RDPG_SEP() \
	_RDPG_had_error   _RDPG_SEP() \
	_RDPG_expect_type _RDPG_SEP() \
	_RDPG_expect_what _RDPG_SEP() \
	)
}
function rdpg_state_set(st,    _arr_st) {
	split(st, _arr_st, _RDPG_SEP())
	_RDPG_curr_tok    = _arr_st[1]
	_RDPG_had_error   = _arr_st[2]
	_RDPG_expect_type = _arr_st[3]
	_RDPG_expect_what = _arr_st[4]
}
# </public>
# <internal>
function _RDPG_SEP() {return "\034"}
function _rdpg_tok_next() {
	_RDPG_curr_tok = tok_next()
}
function _rdpg_tok_is(tok) {
	return (tok == _RDPG_curr_tok)
}
function _rdpg_tok_match(tok,    _ret) {
	if (_ret = _rdpg_tok_is(tok))
		_rdpg_tok_next()
	return _ret
}
function _rdpg_init_sets(    _i, _len, _arr) {
	# alias
	_RDPG_B_str_sym_set_1 = (TOK_EOI() _RDPG_SEP() PTOK_PTREE_DELIM() _RDPG_SEP() TOK_NEW_LINE() _RDPG_SEP() TOK_INCLUDE() _RDPG_SEP() TOK_WORD() _RDPG_SEP() TOK_STRING())
	_RDPG_B_str_sym_set_2 = (PTOK_PTREE_DELIM() _RDPG_SEP() TOK_NEW_LINE() _RDPG_SEP() TOK_INCLUDE() _RDPG_SEP() TOK_WORD() _RDPG_SEP() TOK_STRING())
	_RDPG_B_str_sym_set_3 = (TOK_WORD() _RDPG_SEP() TOK_STRING())
	_RDPG_B_str_sym_set_4 = (TOK_INCLUDE() _RDPG_SEP() TOK_WORD() _RDPG_SEP() TOK_STRING())
	_RDPG_B_str_sym_set_5 = (TOK_WORD() _RDPG_SEP() TOK_STRING() _RDPG_SEP() TOK_INCLUDE())

	_len = split(_RDPG_B_str_sym_set_1, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_1[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_2, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_2[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_3, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_3[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_4, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_4[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_5, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_5[_arr[_i]]

	# expect
	_RDPG_expect_sets["start"] = _RDPG_B_str_sym_set_1
	_RDPG_expect_sets["ptree_item"] = _RDPG_B_str_sym_set_2
	_RDPG_expect_sets["ptree_elem"] = _RDPG_B_str_sym_set_5
	_RDPG_expect_sets["ptree_tree"] = _RDPG_B_str_sym_set_3
	_RDPG_expect_sets["ptree_key"] = _RDPG_B_str_sym_set_3
	_RDPG_expect_sets["ptree_val"] = _RDPG_B_str_sym_set_3
	_RDPG_expect_sets["ptree_wos"] = _RDPG_B_str_sym_set_3
}
function _rdpg_predict(set) {
	return (_RDPG_curr_tok in set)
}
function _rdpg_expect(type, what) {
	_RDPG_expect_type = type
	_RDPG_expect_what = what
	_RDPG_had_error = 1
	tok_err()
}
# </internal>
# <rd>
function _rdpg_start()
{
	# 1. start : ptree_item_star TOK_EOI

	_rdpg_tok_next()
	if (_rdpg_predict(_RDPG_sym_set_1))
	{
		if (_rdpg_ptree_item_star())
		{
			if (_rdpg_tok_match(TOK_EOI()))
			{
				return 1
			}
			else
			{
				_rdpg_expect("tok", TOK_EOI())
			}
		}
	}
	else
	{
		_rdpg_expect("set", "start")
	}
	return 0
}
function _rdpg_ptree_item()
{
	# 2. ptree_item : ptree_nl_star ptree_elem_opt \ptok_insert_ptree_delim PTOK_PTREE_DELIM

	if (_rdpg_predict(_RDPG_sym_set_2))
	{
		if (_rdpg_ptree_nl_star())
		{
			if (_rdpg_ptree_elem_opt())
			{
				ptok_insert_ptree_delim()
				if (_rdpg_tok_match(PTOK_PTREE_DELIM()))
				{
					return 1
				}
				else
				{
					_rdpg_expect("tok", PTOK_PTREE_DELIM())
				}
			}
		}
	}
	else
	{
		_rdpg_expect("set", "ptree_item")
	}
	return 0
}
function _rdpg_ptree_item_star()
{
	# 3. ptree_item_star : ptree_item ptree_item_star
	# 4. ptree_item_star : 0

	while (1)
	{
		if (_rdpg_predict(_RDPG_sym_set_2))
		{
			if (_rdpg_ptree_item())
			{
				continue
			}
		}
		else
		{
			return 1
		}
		return 0
	}
}
function _rdpg_ptree_elem()
{
	# 5. ptree_elem : ptree_tree
	# 6. ptree_elem : ptree_include

	if (_rdpg_predict(_RDPG_sym_set_3))
	{
		if (_rdpg_ptree_tree())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(TOK_INCLUDE()))
	{
		if (_rdpg_ptree_include())
		{
			return 1
		}
	}
	else
	{
		_rdpg_expect("set", "ptree_elem")
	}
	return 0
}
function _rdpg_ptree_elem_opt()
{
	# 7. ptree_elem_opt : ptree_elem
	# 8. ptree_elem_opt : 0

	if (_rdpg_predict(_RDPG_sym_set_4))
	{
		if (_rdpg_ptree_elem())
		{
			return 1
		}
	}
	else
	{
		return 1
	}
	return 0
}
function _rdpg_ptree_tree()
{
	# 9. ptree_tree : ptree_key ptree_val_opt ptree_nl_star ptree_subtree_opt

	if (_rdpg_predict(_RDPG_sym_set_3))
	{
		if (_rdpg_ptree_key())
		{
			if (_rdpg_ptree_val_opt())
			{
				if (_rdpg_ptree_nl_star())
				{
					if (_rdpg_ptree_subtree_opt())
					{
						return 1
					}
				}
			}
		}
	}
	else
	{
		_rdpg_expect("set", "ptree_tree")
	}
	return 0
}
function _rdpg_ptree_key()
{
	# 10. ptree_key : ptree_wos \_ptree_on_key

	if (_rdpg_predict(_RDPG_sym_set_3))
	{
		if (_rdpg_ptree_wos())
		{
			_ptree_on_key()
			return 1
		}
	}
	else
	{
		_rdpg_expect("set", "ptree_key")
	}
	return 0
}
function _rdpg_ptree_val()
{
	# 11. ptree_val : ptree_wos \_ptree_on_val

	if (_rdpg_predict(_RDPG_sym_set_3))
	{
		if (_rdpg_ptree_wos())
		{
			_ptree_on_val()
			return 1
		}
	}
	else
	{
		_rdpg_expect("set", "ptree_val")
	}
	return 0
}
function _rdpg_ptree_val_opt()
{
	# 12. ptree_val_opt : ptree_val
	# 13. ptree_val_opt : 0

	if (_rdpg_predict(_RDPG_sym_set_3))
	{
		if (_rdpg_ptree_val())
		{
			return 1
		}
	}
	else
	{
		return 1
	}
	return 0
}
function _rdpg_ptree_subtree()
{
	# 14. ptree_subtree : TOK_L_CURLY \_ptree_lvl_push ptree_item_star TOK_R_CURLY \_ptree_lvl_pop

	if (_rdpg_tok_is(TOK_L_CURLY()))
	{
		_ptree_lvl_push()
		_rdpg_tok_next()
		if (_rdpg_ptree_item_star())
		{
			if (_rdpg_tok_is(TOK_R_CURLY()))
			{
				_ptree_lvl_pop()
				_rdpg_tok_next()
				return 1
			}
			else
			{
				_rdpg_expect("tok", TOK_R_CURLY())
			}
		}
	}
	else
	{
		_rdpg_expect("tok", TOK_L_CURLY())
	}
	return 0
}
function _rdpg_ptree_subtree_opt()
{
	# 15. ptree_subtree_opt : ptree_subtree
	# 16. ptree_subtree_opt : 0

	if (_rdpg_tok_is(TOK_L_CURLY()))
	{
		if (_rdpg_ptree_subtree())
		{
			return 1
		}
	}
	else
	{
		return 1
	}
	return 0
}
function _rdpg_ptree_include()
{
	# 17. ptree_include : TOK_INCLUDE ptree_string \_ptree_on_include

	if (_rdpg_tok_match(TOK_INCLUDE()))
	{
		if (_rdpg_ptree_string())
		{
			_ptree_on_include()
			return 1
		}
	}
	else
	{
		_rdpg_expect("tok", TOK_INCLUDE())
	}
	return 0
}
function _rdpg_ptree_wos()
{
	# 18. ptree_wos : ptree_word
	# 19. ptree_wos : ptree_string

	if (_rdpg_tok_is(TOK_WORD()))
	{
		if (_rdpg_ptree_word())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(TOK_STRING()))
	{
		if (_rdpg_ptree_string())
		{
			return 1
		}
	}
	else
	{
		_rdpg_expect("set", "ptree_wos")
	}
	return 0
}
function _rdpg_ptree_word()
{
	# 20. ptree_word : TOK_WORD \_ptree_read_word

	if (_rdpg_tok_is(TOK_WORD()))
	{
		_ptree_read_word()
		_rdpg_tok_next()
		return 1
	}
	else
	{
		_rdpg_expect("tok", TOK_WORD())
	}
	return 0
}
function _rdpg_ptree_string()
{
	# 21. ptree_string : TOK_STRING \_ptree_read_string

	if (_rdpg_tok_is(TOK_STRING()))
	{
		_ptree_read_string()
		_rdpg_tok_next()
		return 1
	}
	else
	{
		_rdpg_expect("tok", TOK_STRING())
	}
	return 0
}
function _rdpg_ptree_nl()
{
	# 22. ptree_nl : TOK_NEW_LINE

	if (_rdpg_tok_match(TOK_NEW_LINE()))
	{
		return 1
	}
	else
	{
		_rdpg_expect("tok", TOK_NEW_LINE())
	}
	return 0
}
function _rdpg_ptree_nl_star()
{
	# 23. ptree_nl_star : ptree_nl ptree_nl_star
	# 24. ptree_nl_star : 0

	while (1)
	{
		if (_rdpg_tok_is(TOK_NEW_LINE()))
		{
			if (_rdpg_ptree_nl())
			{
				continue
			}
		}
		else
		{
			return 1
		}
		return 0
	}
}
# </rd>
# </parse>
