.PHONY: help
help:
	@echo 'test  - run tests'
	@echo 'testv - like test but verbose'
	@echo 'help  - this screen'

.PHONY: test
test:
	bash tests/run-tests.sh

.PHONY: testv
testv:
	bash tests/run-tests.sh x
