# generated by tables.awk 1.0
#
# <tables-tables>
#
# prefix tables
#
# defn prefix
# field name
#
# defn defn
# field name
# field field[]
#
# defn field
# field name
# field is_arr
#
# <private>
function _tables_set(k, v) {__TABLES_tables_db__[k] = v}
function _tables_get(k) {return __TABLES_tables_db__[k]}
function _tables_set_count(k, c) {__TABLES_tables_db__[(k ".count")] = c}
function _tables_get_count(k) {return __TABLES_tables_db__[(k ".count")]}
function _tables_set_idx(k, i, v) {__TABLES_tables_db__[(k "." i)] = v}
function _tables_get_idx(k, i,    _x) {
	_x = (k "." i)
	if (_x in __TABLES_tables_db__)
		return __TABLES_tables_db__[_x]
	tables_errq(sprintf("entity '%s': not an index", _x))
}
function _tables_type_chk(ent, texp) {
	if (tables_type_of(ent) == texp)
		return
	tables_errq(sprintf("entity '%s': expected type match '%s', entity type '%s'",
		ent, texp, tables_type_of(ent)))
}
function _tables_new(type,    _ent) {
	_ent = _tables_get("ents")+1
	_tables_set("ents", _ent)
	_ent = ("_tables-" _tables_get("gen")+0 "-" _ent)
	_tables_set(_ent, type)
	return _ent
}
# <\private>

function tables_clear(    _gen) {
	_gen = _tables_get("gen")
	delete __TABLES_tables_db__
	_tables_set("gen", _gen+1)
}
function tables_is(ent) {return (ent in __TABLES_tables_db__)}
function tables_type_of(ent) {
	if (ent in __TABLES_tables_db__)
		return __TABLES_tables_db__[ent]
	tables_errq(sprintf("'%s' not an entity", ent))
}
# <defns>
# <type-prefix>
function TABLES_PREFIX() {return "prefix"}

function prefix_new(    _count, _id, _type) {
	_type = "prefix"
	_id = _tables_new(_type)
	_count = _tables_get_count(_type)+1
	_tables_set_count(_type, _count)
	_tables_set_idx(_type, _count, _id)
	return _id
}
function prefix_get(n) {return _tables_get_idx("prefix", n)}
function prefix_count() {return _tables_get_count("prefix")}
function prefix_last() {return prefix_get(prefix_count())}

function prefix_set_name(prefix_id, name) {
	_tables_type_chk(prefix_id, "prefix")
	_tables_set(("prefix." prefix_id ".name"), name)
}
function prefix_get_name(prefix_id) {
	_tables_type_chk(prefix_id, "prefix")
	return _tables_get(("prefix." prefix_id ".name"))
}
# <\type-prefix>
# <type-defn>
function TABLES_DEFN() {return "defn"}

function defn_new(    _count, _id, _type) {
	_type = "defn"
	_id = _tables_new(_type)
	_count = _tables_get_count(_type)+1
	_tables_set_count(_type, _count)
	_tables_set_idx(_type, _count, _id)
	return _id
}
function defn_get(n) {return _tables_get_idx("defn", n)}
function defn_count() {return _tables_get_count("defn")}
function defn_last() {return defn_get(defn_count())}

function defn_set_name(defn_id, name) {
	_tables_type_chk(defn_id, "defn")
	_tables_set(("defn." defn_id ".name"), name)
}
function defn_get_name(defn_id) {
	_tables_type_chk(defn_id, "defn")
	return _tables_get(("defn." defn_id ".name"))
}

function defn_add_field(defn_id, field,    _count, _n) {
	_tables_type_chk(defn_id, "defn")
	_n = ("defn." defn_id ".field")
	_count = _tables_get_count(_n)+1
	_tables_set_count(_n, _count)
	_tables_set_idx(_n, _count, field)
}
function defn_get_field(defn_id, n) {
	_tables_type_chk(defn_id, "defn")
	return _tables_get_idx(("defn." defn_id ".field"), n)
}
function defn_set_field(defn_id, n, field) {
	_tables_type_chk(defn_id, "defn")
	return _tables_set_idx(("defn." defn_id ".field"), n, field)
}
function defn_count_field(defn_id) {
	_tables_type_chk(defn_id, "defn")
	return _tables_get_count(("defn." defn_id ".field"))
}
function defn_last_field(defn_id) {
	return defn_get_field(defn_id, defn_count_field(defn_id))
}
# <\type-defn>
# <type-field>
function TABLES_FIELD() {return "field"}

function field_new(    _count, _id, _type) {
	_type = "field"
	_id = _tables_new(_type)
	_count = _tables_get_count(_type)+1
	_tables_set_count(_type, _count)
	_tables_set_idx(_type, _count, _id)
	return _id
}
function field_get(n) {return _tables_get_idx("field", n)}
function field_count() {return _tables_get_count("field")}
function field_last() {return field_get(field_count())}

function field_set_name(field_id, name) {
	_tables_type_chk(field_id, "field")
	_tables_set(("field." field_id ".name"), name)
}
function field_get_name(field_id) {
	_tables_type_chk(field_id, "field")
	return _tables_get(("field." field_id ".name"))
}

function field_set_is_arr(field_id, is_arr) {
	_tables_type_chk(field_id, "field")
	_tables_set(("field." field_id ".is_arr"), is_arr)
}
function field_get_is_arr(field_id) {
	_tables_type_chk(field_id, "field")
	return _tables_get(("field." field_id ".is_arr"))
}
# <\type-field>
# <\defns>
# <\tables-tables>
