#!/usr/bin/awk -f

# generated by smpg.awk 2.1

# <description>
function DESCRIPT_INCLUDES() {
return \
"included files:\n"\
"awklib_prog.awk\n"\
"awklib_tabs.awk\n"\
}
function DESCRIPT_FSM() {
return \
"fsm rules:\n"\
"start  -> prefix | type | union\n"\
"prefix -> type | union\n"\
"type   -> has\n"\
"has    -> has  | type | union | end\n"\
"union  -> name\n"\
"name   -> name | type | union | end\n"\
"end    -> start\n"\
"\n"\
"'->' is read as 'must be followed by'\n"\
"'|' is read as 'or'"
}
function DESCRIPT() {
	return (DESCRIPT_INCLUDES() "\n" DESCRIPT_FSM())
}
# </description>

# <other>
# Author: Vladimir Dinev
# vld.dinev@gmail.com

function SCRIPT_NAME()    {return "structs.awk"}
function SCRIPT_VERSION() {return "2.1"}

# <awk_rules>
function init() {
	set_program_name(SCRIPT_NAME())

	if (Fsm)
		print_fsm()
	if (Help)
		print_help()
	if (Version)
		print_version()
	if (ARGC != 2)
		print_use_try()
}

function leave() {
	if (!should_skip_end()) {
		fsm_get_state(G_the_fsm)
		if (fsm_get_state(G_the_fsm) != FSM_END())
			fsm_on_error("", FSM_END(), fsm_get_state(G_the_fsm))
	}
}

BEGIN {
	init()
}

# ignore empty lines and comments
/^[[:space:]]*(#|$)/ {next}

# strip spaces and fsm
{
	gsub("^[[:space:]]+|[[:space:]]+$", "", $0)
	fsm_next(G_the_fsm, $1)
}

END {
	leave()
}
# </awk_rules>

function data_or_err() {
	if (NF < 2)
		error_qfpos(sprintf("no data after '%s'", $1))
}
function error_qfpos(msg) {
	error_quit(sprintf("file '%s' line %d: %s", FILENAME, FNR, msg))
}
# </other>

# <templated>
# 'prefix|type|union|name'
function on_prefix(v) {prefix_save(v)}

function on_type(v) {type_save(v)}

function on_union(v) {union_save(v)}

function on_name(v) {name_save(v)}

# 'has'
function on_has(memb, type) {has_save(memb, type)}
# </templated>

# <fsm>
# <handlers>
function fsm_on_start() {
	prefix_save("ent")
}
function fsm_on_prefix() {
	data_or_err()
	on_prefix($2)
}
function fsm_on_type() {
	data_or_err()
	on_type($2)
}
function fsm_on_has() {
	data_or_err()
	on_has($2, $3)
}
function fsm_on_union() {
	data_or_err()
	on_union($2)
}
function fsm_on_name() {
	data_or_err()
	on_name($2)
}
function fsm_on_end() {
	generate()
	exit_success()
}
function fsm_on_error(curr_st, expected, got) {
	error_qfpos(sprintf("expected '%s', got '%s'", expected, got))
}
# </handlers>

# <constants>
function FSM_START() {return "start"}
function FSM_PREFIX() {return "prefix"}
function FSM_TYPE() {return "type"}
function FSM_HAS() {return "has"}
function FSM_UNION() {return "union"}
function FSM_NAME() {return "name"}
function FSM_END() {return "end"}
function _FSM_STATE() {return "state"}
# </constants>

# <functions>
function fsm_get_state(fsm) {return fsm[_FSM_STATE()]}
function _fsm_set_state(fsm, next_st) {fsm[_FSM_STATE()] = next_st}
function fsm_next(fsm, next_st,    _st) {

	_st = fsm_get_state(fsm)
	if ("" == _st) {
		if (FSM_START() == next_st)
		{fsm_on_start(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_START(), next_st)}
	}
	else if (FSM_START() == _st) {
		if (FSM_PREFIX() == next_st)
		{fsm_on_prefix(); _fsm_set_state(fsm, next_st)}
		else if (FSM_TYPE() == next_st)
		{fsm_on_type(); _fsm_set_state(fsm, next_st)}
		else if (FSM_UNION() == next_st)
		{fsm_on_union(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_PREFIX()"|"FSM_TYPE()"|"FSM_UNION(), next_st)}
	}
	else if (FSM_PREFIX() == _st) {
		if (FSM_TYPE() == next_st)
		{fsm_on_type(); _fsm_set_state(fsm, next_st)}
		else if (FSM_UNION() == next_st)
		{fsm_on_union(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_TYPE()"|"FSM_UNION(), next_st)}
	}
	else if (FSM_TYPE() == _st) {
		if (FSM_HAS() == next_st)
		{fsm_on_has(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_HAS(), next_st)}
	}
	else if (FSM_HAS() == _st) {
		if (FSM_HAS() == next_st)
		{fsm_on_has(); _fsm_set_state(fsm, next_st)}
		else if (FSM_TYPE() == next_st)
		{fsm_on_type(); _fsm_set_state(fsm, next_st)}
		else if (FSM_UNION() == next_st)
		{fsm_on_union(); _fsm_set_state(fsm, next_st)}
		else if (FSM_END() == next_st)
		{fsm_on_end(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_HAS()"|"FSM_TYPE()"|"FSM_UNION()"|"FSM_END(), next_st)}
	}
	else if (FSM_UNION() == _st) {
		if (FSM_NAME() == next_st)
		{fsm_on_name(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_NAME(), next_st)}
	}
	else if (FSM_NAME() == _st) {
		if (FSM_NAME() == next_st)
		{fsm_on_name(); _fsm_set_state(fsm, next_st)}
		else if (FSM_TYPE() == next_st)
		{fsm_on_type(); _fsm_set_state(fsm, next_st)}
		else if (FSM_UNION() == next_st)
		{fsm_on_union(); _fsm_set_state(fsm, next_st)}
		else if (FSM_END() == next_st)
		{fsm_on_end(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_NAME()"|"FSM_TYPE()"|"FSM_UNION()"|"FSM_END(), next_st)}
	}
	else if (FSM_END() == _st) {
		if (FSM_START() == next_st)
		{fsm_on_start(); _fsm_set_state(fsm, next_st)}
		else
		{fsm_on_error(_st, FSM_START(), next_st)}
	}
}
# </functions>
# </fsm>

# <includes>
# ../awklib/src/awklib_prog.awk
#@ <awklib_prog>
#@ Library: prog
#@ Description: Provides program name, error, and exit handling.
#@ Version 1.0
##
## Vladimir Dinev
## vld.dinev@gmail.com
## 2021-08-15
#@

#
#@ Description: Sets the program name to 'str'. This name can later be
#@ retrieved by get_program_name().
#@ Returns: Nothing.
#
function set_program_name(str) {

	_AWKLIB_prog__program_name = str
}

#
#@ Description: Provides the program name.
#@ Returns: The name as set by set_program_name().
#
function get_program_name() {

	return _AWKLIB_prog__program_name
}

#
#@ Description: Prints 'msg' to stderr.
#@ Returns: Nothing.
#
function pstderr(msg) {

	print msg > "/dev/stderr"
}

#
#@ Description: Sets a static flag which can later be checked by
#@ should_skip_end().
#@ Returns: Nothing.
#
function skip_end_set() {

	_AWKLIB_prog__skip_end_flag = 1
}

#
#@ Description: Clears the flag set by skip_end_set().
#@ Returns: Nothing.
#
function skip_end_clear() {

	_AWKLIB_prog__skip_end_flag = 0
}

#
#@ Description: Checks the static flag set by skip_end_set().
#@ Returns: 1 if the flag is set, 0 otherwise.
#
function should_skip_end() {

	return (_AWKLIB_prog__skip_end_flag+0)
}

#
#@ Description: Sets a static flag which can later be checked by
#@ did_error_happen().
#@ Returns: Nothing
#
function error_flag_set() {

	_AWKLIB_prog__error_flag = 1
}

#
#@ Description: Clears the flag set by error_flag_set().
#@ Returns: Nothing
#
function error_flag_clear() {

	_AWKLIB_prog__error_flag = 0
}

#
#@ Description: Checks the static flag set by error_flag_set().
#@ Returns: 1 if the flag is set, 0 otherwise.
#
function did_error_happen() {

	return (_AWKLIB_prog__error_flag+0)
}

#
#@ Description: Sets the skip end flag, exits with error code 0.
#@ Returns: Nothing.
#
function exit_success() {

	skip_end_set()
	exit(0)
}

#
#@ Description: Sets the skip end flag, exits with 'code', or 1 if 'code' is 0
#@ or not given.
#@ Returns: Nothing.
#
function exit_failure(code) {

	skip_end_set()
	exit((code+0) ? code : 1)
}

#
#@ Description: Prints '<program-name>: error: msg' to stderr. Sets the
#@ error and skip end flags.
#@ Returns: Nothing.
#
function error_print(msg) {

	pstderr(sprintf("%s: error: %s", get_program_name(), msg))
	error_flag_set()
	skip_end_set()
}

#
#@ Description: Calls error_print() and quits with failure.
#@ Returns: Nothing.
#
function error_quit(msg, code) {

	error_print(msg)
	exit_failure(code)
}
#@ </awklib_prog>
# ../awklib/src/awklib_tabs.awk
#@ <awklib_tabs>
#@ Library: tabs
#@ Description: String indentation.
#@ Version: 1.0
##
## Vladimir Dinev
## vld.dinev@gmail.com
## 2021-08-16
#@

#
#@ Description: Adds a tab to the indentation string.
#@ Returns: Nothing.
#
function tabs_inc() {

	++_AWKLIB_tabs__tabs_num
	_AWKLIB_tabs__tabs_str = (_AWKLIB_tabs__tabs_str "\t")
}

#
#@ Description: Removes a tab from the indentation string.
#@ Returns: Nothing.
#
function tabs_dec() {

	if (_AWKLIB_tabs__tabs_num) {
		--_AWKLIB_tabs__tabs_num
		_AWKLIB_tabs__tabs_str = substr(_AWKLIB_tabs__tabs_str, 1,
			_AWKLIB_tabs__tabs_num)
	}
}

#
#@ Description: Indicates the tab level.
#@ Returns: The number of tabs used for indentation.
#
function tabs_num() {

	return _AWKLIB_tabs__tabs_num
}

#
#@ Description: Provides all indentation tabs as a string.
#@ Returns: The indentation string.
#
function tabs_get() {

	return (_AWKLIB_tabs__tabs_str "")
}

#
#@ Description: Adds indentation to 'str'.
#@ Returns: 'str' prepended with the current number of tabs.
#
function tabs_indent(str) {

	return (_AWKLIB_tabs__tabs_str str)
}

#
#@ Description: Prints the indented 'str' to stdout without a new line
#@ at the end.
#@ Returns: Nothing.
#
function tabs_print_str(str) {

	printf("%s", tabs_indent(str))
}

#
#@ Description: Prints the indented 'str' to stdout with a new line at
#@ the end.
#@ Returns: Nothing.
#
function tabs_print(str) {

	print tabs_indent(str)
}
#@ </awklib_tabs>
# </includes>
# <generate>
# <data>
function __set(k, v) {_B_structs[k] = v}
function __get(k) {return _B_structs[k]}
function __has(k) {return (k in _B_structs)}

function prefix_save(str) {__set("prefix", str)}
function prefix_get() {return __get("prefix")}

function type_save(str,    _count) {
	_count = __get("type.count") + 1
	__set("type.count", _count)
	__set(sprintf("type.%d", _count), str)
	__set(sprintf("type.set=%s", str))
}
function type_count() {return __get("type.count")}
function type_get(n)  {return __get(sprintf("type.%d", n))}
function type_last()  {return type_get(type_count())}
function type_is(str) {return __has(sprintf("type.set=%s", str))}

function has_save(memb, mtype,    _type, _count, _key) {
	_type = type_last()

	_key = sprintf("has.count.%s", _type)
	_count = __get(_key) + 1
	__set(_key, _count)

	__set(sprintf("has.memb.%d.%s", _count, _type), memb)
	has_set_mtype(_type, _count, mtype)
}
function has_count(type) {
	return __get(sprintf("has.count.%s", type))
}
function has_set_mtype(type, n, mtype) {
	__set(sprintf("has.mtype.%d.%s", n, type), mtype)
}
function has_get_memb(type, n) {
	return __get(sprintf("has.memb.%d.%s", n, type))
}
function has_get_mtype(type, n) {
	return __get(sprintf("has.mtype.%d.%s", n, type))
}

function union_save(str,    _count) {
	_count = __get("union.count") + 1
	__set("union.count", _count)
	__set(sprintf("union.%d", _count), str)
	__set(sprintf("union.set=%s", str))
}
function union_count() {return __get("union.count")}
function union_get(n)  {return __get(sprintf("union.%d", n))}
function union_last()  {return union_get(union_count())}
function union_is(str) {return __has(sprintf("union.set=%s", str))}

function name_save(str,    _union, _count, _key) {
	_union = union_last()

	_key = sprintf("name.count.%s", _union)
	_count = __get(_key) + 1
	__set(_key, _count)

	__set(sprintf("name.%d.%s", _count, _union), str)
}
function name_count(union)  {return __get(sprintf("name.count.%s", union))}
function name_get(union, n) {return __get(sprintf("name.%d.%s", n, union))}
# </data>

function tag_structs() {return ("structs-" prefix_get())}
function tag_open(tag) {print sprintf("# <%s>", tag)}
function tag_close(tag) {print sprintf("# <\\%s>", tag)}
function make_fnm(str,    _pref) {return (prefix_get() "_" str)}
function make_dbnm() {return sprintf("_STRUCTS_%s_db", prefix_get())}

function emit(str) {tabs_print(str)}

function gen_base(    _fname, _db_nm) {
	tag_open("private")
	_db_nm = make_dbnm()

	_fname = ("_" make_fnm("set"))
	emit(sprintf("function %s(k, v) {%s[k] = v}", _fname, _db_nm))

	_fname = ("_" make_fnm("get"))
	emit(sprintf("function %s(k) {return %s[k]}", _fname, _db_nm))

	_fname = ("_" make_fnm("type_chk"))
	emit(sprintf("function %s(ent, texp) {", _fname))
	tabs_inc()
		emit(sprintf("if (%s(ent) ~ texp)", make_fnm("type_of")))
			tabs_inc()
			emit("return")
			tabs_dec()
		emit(                                                                 \
			sprintf(                                                          \
				(                                                             \
				"%s_errq(sprintf(\"entity '%%s': expected type match '%%s', " \
				"entity type '%%s'\", \n\t\t ent, texp, %s(ent)))"            \
				),                                                            \
				prefix_get(),                                                 \
				make_fnm("type_of")                                           \
			)                                                                 \
		)
	tabs_dec()
	emit("}")
	tag_close("private")

	emit("")

	_fname = make_fnm("clear")
	emit(sprintf("function %s() {", _fname))
	tabs_inc()
		emit(sprintf("delete %s", _db_nm))
		emit(                                   \
			sprintf(                            \
				"_%s(\"gen\", _%s(\"gen\")+1)", \
				make_fnm("set"),                \
				make_fnm("get")                 \
			)                                   \
		)
	tabs_dec()
	emit("}")

	_fname = make_fnm("is")
	emit(sprintf("function %s(ent) {return (ent in %s)}", _fname, _db_nm))

	_fname = make_fnm("type_of")
	emit(sprintf("function %s(ent) {", _fname))
	tabs_inc()
		emit(sprintf("if (ent in %s)", _db_nm))
		tabs_inc()
			emit(sprintf("return %s[ent]", _db_nm, _db_nm))
		tabs_dec()
		emit(                                                     \
			sprintf(                                              \
				"%s_errq(sprintf(\"'%%s' not an entity\", ent))", \
				prefix_get()                                      \
			)                                                     \
		)
	tabs_dec()
	emit("}")

	_fname = make_fnm("new")
	emit(sprintf("function %s(type,    _ent) {", _fname))
	tabs_inc()
		emit(                                              \
			sprintf(                                       \
				"_%s(\"ents\", (_ent = _%s(\"ents\")+1))", \
				make_fnm("set"),                           \
				make_fnm("get")                            \
			)                                              \
		)
		emit(                                                  \
			sprintf(                                           \
				"_ent = (\"_%s-\" _%s(\"gen\")+0 \"-\" _ent)", \
				prefix_get(),                                  \
				make_fnm("get")                                \
			)                                                  \
		)
		emit(sprintf("_%s(_ent, type)", make_fnm("set")))
		emit("return _ent")
	tabs_dec()
	emit("}")
}

function gen_type(type,    _i, _end, _memb, _mtype, _pref, _fname, _type_rx) {
	_pref = prefix_get()
	_end = has_count(type)
	_fname = sprintf("function %s_make(", make_fnm(type))
	for (_i = 1; _i <= _end; ++_i)
		_fname = (_fname sprintf("%s, ", has_get_memb(type, _i)))
	emit(sprintf("%s    _ent) {", _fname))
	tabs_inc()
		emit(sprintf("_ent = %s(\"%s\")", make_fnm("new"), type))
		for (_i = 1; _i <= _end; ++_i) {
			_memb = has_get_memb(type, _i)
			_fname = sprintf("%s_%s_set_%s", _pref, type, _memb)
			emit(sprintf("%s(_ent, %s)", _fname, _memb))
		}
		emit("return _ent")
	tabs_dec()
	emit("}")
	emit("")

	_type_rx = sprintf("^(%s)$", type)
	for (_i = 1; _i <= _end; ++_i) {
		_memb = has_get_memb(type, _i)
		_mtype = has_get_mtype(type, _i)

		_fname = sprintf("%s_%s_set_%s", _pref, type, _memb)
		emit(sprintf("function %s(ent, %s) {", _fname, _memb))
		tabs_inc()
			emit(sprintf("_%s(ent, \"%s\")", make_fnm("type_chk"), _type_rx))
			if (_mtype) {
				emit(sprintf("if (%s)", _memb))
				tabs_inc()
					emit(                             \
						sprintf(                      \
							"_%s(%s, \"%s\")",        \
							make_fnm("type_chk"),     \
							_memb,                    \
							sprintf("^(%s)$", _mtype) \
						)                             \
					)
				tabs_dec()
			}
			emit(                             \
				sprintf(                      \
					"_%s((ent \".%s\"), %s)", \
					make_fnm("set"),          \
					_memb,                    \
					_memb                     \
				)                             \
			)
		tabs_dec()
		emit("}")

		_fname = sprintf("%s_%s_get_%s", _pref, type, _memb)
		emit(sprintf("function %s(ent) {", _fname))
		tabs_inc()
			emit(sprintf("_%s(ent, \"%s\")", make_fnm("type_chk"), _type_rx))
			emit(sprintf("return _%s((ent \".%s\"))", make_fnm("get"), _memb))
		tabs_dec()
		emit("}")
		emit("")
	}
}

function gen_types(    _i, _end, _type, _fname) {
	_end = type_count()
	for (_i = 1; _i <= _end; ++_i) {
		_type = type_get(_i)
		_fname = toupper(make_fnm(_type))
		tag_open(sprintf("type-%s", _type))
		emit(sprintf("function %s() {return \"%s\"}", _fname, _type))
		emit("")
		gen_type(_type)
		tag_close(sprintf("type-%s", _type))
	}
}

# <checks>
function errq_does_not_name(msg) {
	error_quit(sprintf("%s does not name a type nor an union", msg))
}
function errq_redefined(msg) {
	error_quit(sprintf("%s defined more than once", msg))
}
# <types>
function check_types(    _i, _end, _type, _set) {
	_end = type_count()

	if (!_end)
		check_types_no_types_fail()

	for (_i = 1; _i <= _end; ++_i) {
		_type = type_get(_i)

		if (!(_type in _set))
			_set[_type]
		else
			check_types_redefined_fail(_type)

		if (union_is(_type))
			check_types_both_fail(_type)

		check_types_type_of_members(_type)
		check_types_unique_members(_type)
	}
}
function check_types_no_types_fail() {
	error_quit("no defined types")
}
function check_types_redefined_fail(type) {
	errq_redefined(sprintf("type '%s'", type))
}
function check_types_both_fail(type) {
	error_quit(sprintf("name '%s' defined as both an union and a type", type))
}

function check_types_type_of_members(type,    _i, _end, _mtype) {
	_end = has_count(type)
	for (_i = 1; _i <= _end; ++_i) {
		_mtype = has_get_mtype(type, _i)
		if (_mtype && !type_is(_mtype) && !union_is(_mtype)) {
			check_types_type_of_members_fail( \
				type,                         \
				has_get_memb(type, _i),       \
				_mtype                        \
			)
		}
	}
}
function check_types_type_of_members_fail(type, memb, mtype) {
	errq_does_not_name(                     \
		sprintf(                            \
			"type '%s', member '%s': '%s'", \
			type,                           \
			memb,                           \
			mtype                           \
		)                                   \
	)
}

function check_types_unique_members(type,    _i, _end, _memb, _set) {
	_end = has_count(type)
	for (_i = 1; _i <= _end; ++_i) {
		_memb = has_get_memb(type, _i)
		if (!(_memb in _set))
			_set[_memb]
		else
			check_types_unique_members_fail(type, _memb)
	}
}
function check_types_unique_members_fail(type, memb) {
	errq_redefined(sprintf("type '%s': member '%s'", type, memb))
}
# </types>

# <unions>
function check_unions(    _i, _end, _union, _set) {
	_end = union_count()
	for (_i = 1; _i <= _end; ++_i) {
		_union = union_get(_i)

		if (!(_union in _set))
			_set[_union]
		else
			check_unions_redefined_fail(_union)

		check_unions_type_of_names(_union)
		check_unions_unique_names(_union)
	}
}
function check_unions_redefined_fail(union) {
	errq_redefined(sprintf("union '%s'", union))
}

function check_unions_type_of_names(union,    _i, _end, _name) {
	_end = name_count(union)
	for (_i = 1; _i <= _end; ++_i) {
		_name = name_get(union, _i)
		if (!type_is(_name) && !union_is(_name))
			check_unions_type_of_names_fail(union, _name)
	}
}
function check_unions_type_of_names_fail(union, name) {
	errq_does_not_name(sprintf("union '%s': name '%s'", union, name))
}

function check_unions_unique_names(union, _path, _set,    _i, _end, _name,
_guard) {
	_guard = (" " union " ")
	if (index(_path, _guard))
		check_unions_unique_names_recurse_fail(_path, _guard)

	_path = !(_path) ? (" " union) : (_path " -> " union)

	_end = name_count(union)
	for (_i = 1; _i <= _end; ++_i) {
		_name = name_get(union, _i)

		if (!(_name in _set)) {
			_set[_name] = union
		} else {
			check_unions_unique_names_repeat_fail( \
				_name,                             \
				_set[_name],                       \
				union,                             \
				_path                              \
			)
		}

		if (union_is(_name))
			check_unions_unique_names(_name, _path, _set)
	}
}
function check_unions_unique_names_recurse_fail(path, guard) {
	error_quit(sprintf("recursive reference of unions:%s->%s", path, guard))
}
function check_unions_unique_names_repeat_fail(name, union_start, union_end,
path) {
	error_print(sprintf("multiple occurrences of name '%s'", name))
	pstderr(sprintf("first union: %s", union_start))
	pstderr(sprintf("last  union: %s", union_end))
	pstderr(sprintf("path:%s", path))
	exit_failure()
}
# </unions>

function do_checks() {
	check_types()
	check_unions()
}
# </checks>

# <resolve>
function resolved_union_save(union, types) {
	_B_resolved_union_tbl[union] = types
	_B_resolved_union_rev_tbl[types] = union
}
function resolved_union_is(union) {
	return (union in _B_resolved_union_tbl)
}
function resolved_union_get(union) {
	return (union in _B_resolved_union_tbl) ? _B_resolved_union_tbl[union] : ""
}
function resolved_union_get_rev(types) {
	return (types in _B_resolved_union_rev_tbl) \
			? _B_resolved_union_rev_tbl[types] : ""
}

function resolve_unions_of_types(    _i, _end) {
	_end = type_count()
	for (_i = 1; _i <= _end; ++_i)
		resolve_unions_of_type_members(type_get(_i))
}

function resolve_unions_of_type_members(type,    _i, _end, _mtype) {
	_end = has_count(type)
	for (_i = 1; _i <= _end; ++_i) {
		_mtype = has_get_mtype(type, _i)
		if (union_is(_mtype)) {
			if (!resolved_union_is(_mtype))
				resolved_union_save(_mtype, resolve_union(_mtype))
			has_set_mtype(type, _i, resolved_union_get(_mtype))
		}
	}
}

function resolve_union(union, _types,    _i, _end, _name, _next) {
	_end = name_count(union)
	for (_i = 1; _i <= _end; ++_i) {
		_name = name_get(union, _i)

		if (type_is(_name))
			_next = _name
		else if (union_is(_name))
			_next = resolve_union(_name)
		else
			error_quit("if you see this there's a bug")

		_types = !(_types) ? _next : (_types "|" _next)
	}
	return _types
}

function resolve_unions_to_types() {
	resolve_unions_of_types()
}
# </resolve>

# <header>
function gen_union_cmnts(    _i, _end, _union) {
	_end = union_count()
	for (_i = 1; _i <= _end; ++_i) {
		_union = union_get(_i)
		emit("#")
		emit(sprintf("# union %s", _union))
		gen_union_name_cmnts(_union)
	}
}
function gen_union_name_cmnts(union,    _i, _end) {
	_end = name_count(union)
	for (_i = 1; _i <= _end; ++_i)
		emit(sprintf("# name %s", name_get(union, _i)))
}

function gen_type_cmnts(    _i, _end, _type) {
	_end = type_count()
	for (_i = 1; _i <= _end; ++_i) {
		_type = type_get(_i)
		emit("#")
		emit(sprintf("# type %s", _type))
		gen_type_memb_cmnts(_type)
	}
}
function gen_type_memb_cmnts(type,    _i, _end, _memb, _mtype, _rev_union) {
	_end = has_count(type)
	for (_i = 1; _i <= _end; ++_i) {
		_memb = has_get_memb(type, _i)
		_mtype = has_get_mtype(type, _i)
		if ((_rev_union = resolved_union_get_rev(_mtype))) {
			emit(sprintf("# # %s is %s", _rev_union, _mtype))
			emit(sprintf("# has %s %s", _memb, _rev_union))
		} else {
			emit(sprintf("# has %s %s", _memb, _mtype))
		}
	}
}

function gen_header_cmnt() {
	emit(sprintf("# generated by %s %s", SCRIPT_NAME(), SCRIPT_VERSION()))
	emit("#")
}

function gen_struct_cmnts() {
	emit("#")
	emit(sprintf("# prefix %s", prefix_get()))
	gen_union_cmnts()
	gen_type_cmnts()
	emit("#")
}
# </header>

function generate() {
	do_checks()
	resolve_unions_to_types()
	gen_header_cmnt()
	tag_open(tag_structs())
	gen_struct_cmnts()
	gen_base()
	tag_open("types")
	gen_types()
	tag_close("types")
	tag_close(tag_structs())
}
# </generate>
# <doc>
function print_help() {
print sprintf("%s - type compiler", SCRIPT_NAME())
print ""
print use_str()
print ""
print "Compiles type descriptions into a type system in awk. 'Compiles in awk'"
print "means it generates awk source code for setters/getters for each type's"
print "members, along with functions to create a variable of a certain type,"
print "check its type, and a table to remember what values all its members"
print "have. For a starter example use the following as an input file:"
print ""
print "start"
print "type btree"
print "has  data"
print "has  left  btree"
print "has  right btree"
print "end"
print ""
print "Unions of type names and prefixing are supported. Unions can refer to"
print "other unions. E.g. in"
print ""
print "start"
print ""
print "prefix ast"
print ""
print "type uint"
print "has  val"
print ""
print "type int"
print "has  val"
print ""
print "type double"
print "has  val"
print ""
print "union u_signed"
print "name  int"
print "name  double"
print ""
print "union u_number"
print "name  uint"
print "name  u_signed"
print ""
print "type number"
print "has node u_number"
print ""
print "end"
print ""
print "member 'node' in a variable of type 'number' can be of either type uint,"
print "int, or double. To set 'node' to a variable of any other type will be an"
print "error. Because of the prefix option, all generated function names will"
print "be prefixed by 'ast_', e.g."
print "ast_number_make(), ast_number_set_node(), ast_number_get_node() etc."
print "The default prefix is 'ent_'"
print ""
print "The user must define an error function which the generated code can call."
print "In the prefixed example the function looks like: ast_errq(msg)"
print ""
print "Options:"
print "-vFsm=1     - print the fsm grammar"
print "-vVersion=1 - version information"
print "-vHelp=1    - this screen"
exit_success()
}
function print_fsm() {
	print DESCRIPT_FSM()
	exit_success()
}
function print_version() {
	print sprintf("%s %s", SCRIPT_NAME(), SCRIPT_VERSION())
	exit_success()
}
function use_str() {
	return sprintf("Use: %s <structs-file>", SCRIPT_NAME())
}
function print_use_try() {
	pstderr(use_str())
	pstderr(sprintf("Try: %s -vHelp=1", SCRIPT_NAME()))
	exit_failure()
}
# </doc>
