# <parse>
#
# translated by rdpg-to-awk.awk 2.1.3
# generated by rdpg-comp.awk 2.2.3
# 
# Immediate error detection: 1
# 
# Grammar:
# 
# 1. start : _json _TOK_EOI
# 
# 2. _json : _element
# 
# 3. _element : _object
# 4. _element : _array
# 5. _element : _string
# 6. _element : _number
# 7. _element : _bool
# 8. _element : _null
# 
# 9. _object : _TOK_LCURL \_prs_usr_on_obj_start _members_opt _TOK_RCURL \_prs_usr_on_obj_end
# 
# 10. _array : _TOK_LSQR \_prs_usr_on_arr_start _elements_opt _TOK_RSQR \_prs_usr_on_arr_end
# 
# 11. _string : _TOK_STRING \_prs_usr_on_string
# 
# 12. _number : _TOK_NUMBER \_prs_usr_on_number
# 
# 13. _bool : _TOK_TRUE \_prs_usr_on_bool
# 14. _bool : _TOK_FALSE \_prs_usr_on_bool
# 
# 15. _null : _TOK_NULL \_prs_usr_on_null
# 
# 16. _elements : _element _elements_rest_star
# 
# 17. _elements_opt : _elements
# 18. _elements_opt : 0
# 
# 19. _elements_rest : _TOK_COMMA _element
# 
# 20. _elements_rest_star : _elements_rest _elements_rest_star
# 21. _elements_rest_star : 0
# 
# 22. _members : _member _members_rest_star
# 
# 23. _members_opt : _members
# 24. _members_opt : 0
# 
# 25. _member : _TOK_STRING \_prs_usr_on_member_name _TOK_COLON _element
# 
# 26. _members_rest : _TOK_COMMA _member
# 
# 27. _members_rest_star : _members_rest _members_rest_star
# 28. _members_rest_star : 0
# 

# <public>
function rdpg_parse()
{
	_rdpg_init_sets()
	return _rdpg_start() && !_RDPG_had_error
}
function rdpg_expect(arr_out,    _len) {
	delete arr_out
	if ("tok" == _RDPG_expect_type)
		arr_out[(_len = 1)] = _RDPG_expect_what
	else if ("set" == _RDPG_expect_type)
		_len = split(_RDPG_expect_sets[_RDPG_expect_what], arr_out, _RDPG_SEP())
	return _len
}
# </public>
# <internal>
function _RDPG_SEP() {return "\034"}
function _rdpg_tok_next() {
	_RDPG_curr_tok = tok_next()
}
function _rdpg_tok_is(tok) {
	return (tok == _RDPG_curr_tok)
}
function _rdpg_tok_match(tok,    _ret) {
	if (_ret = _rdpg_tok_is(tok))
		_rdpg_tok_next()
	return _ret
}
function _rdpg_init_sets(    _i, _len, _arr) {
	# alias
	_RDPG_B_str_sym_set_1 = (_TOK_LCURL() _RDPG_SEP() _TOK_LSQR() _RDPG_SEP() _TOK_STRING() _RDPG_SEP() _TOK_NUMBER() _RDPG_SEP() _TOK_TRUE() _RDPG_SEP() _TOK_FALSE() _RDPG_SEP() _TOK_NULL())
	_RDPG_B_str_sym_set_2 = (_TOK_TRUE() _RDPG_SEP() _TOK_FALSE())
	_RDPG_B_str_sym_set_3 = (_TOK_LCURL() _RDPG_SEP() _TOK_LSQR() _RDPG_SEP() _TOK_STRING() _RDPG_SEP() _TOK_NUMBER() _RDPG_SEP() _TOK_TRUE() _RDPG_SEP() _TOK_FALSE() _RDPG_SEP() _TOK_NULL() _RDPG_SEP() _TOK_RSQR())
	_RDPG_B_str_sym_set_4 = (_TOK_COMMA() _RDPG_SEP() _TOK_RSQR())
	_RDPG_B_str_sym_set_5 = (_TOK_STRING() _RDPG_SEP() _TOK_RCURL())
	_RDPG_B_str_sym_set_6 = (_TOK_COMMA() _RDPG_SEP() _TOK_RCURL())

	_len = split(_RDPG_B_str_sym_set_1, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_1[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_2, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_2[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_3, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_3[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_4, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_4[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_5, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_5[_arr[_i]]

	_len = split(_RDPG_B_str_sym_set_6, _arr, _RDPG_SEP())
	for (_i = 1; _i <= _len; ++_i)
		_RDPG_sym_set_6[_arr[_i]]

	# expect
	_RDPG_expect_sets["start"] = _RDPG_B_str_sym_set_1
	_RDPG_expect_sets["_json"] = _RDPG_B_str_sym_set_1
	_RDPG_expect_sets["_element"] = _RDPG_B_str_sym_set_1
	_RDPG_expect_sets["_bool"] = _RDPG_B_str_sym_set_2
	_RDPG_expect_sets["_elements"] = _RDPG_B_str_sym_set_1
	_RDPG_expect_sets["_elements_opt"] = _RDPG_B_str_sym_set_3
	_RDPG_expect_sets["_elements_rest_star"] = _RDPG_B_str_sym_set_4
	_RDPG_expect_sets["_members_opt"] = _RDPG_B_str_sym_set_5
	_RDPG_expect_sets["_members_rest_star"] = _RDPG_B_str_sym_set_6
}
function _rdpg_predict(set) {
	return (_RDPG_curr_tok in set)
}
function _rdpg_expect(type, what) {
	_RDPG_expect_type = type
	_RDPG_expect_what = what
	_RDPG_had_error = 1
	tok_err()
}
# </internal>
# <rd>
function _rdpg_start()
{
	# 1. start : _json _TOK_EOI

	_rdpg_tok_next()
	if (_rdpg_predict(_RDPG_sym_set_1))
	{
		if (_rdpg__json())
		{
			if (_rdpg_tok_match(_TOK_EOI()))
			{
				return 1
			}
			else
			{
				_rdpg_expect("tok", _TOK_EOI())
			}
		}
	}
	else
	{
		_rdpg_expect("set", "start")
	}
	return 0
}
function _rdpg__json()
{
	# 2. _json : _element

	if (_rdpg_predict(_RDPG_sym_set_1))
	{
		if (_rdpg__element())
		{
			return 1
		}
	}
	else
	{
		_rdpg_expect("set", "_json")
	}
	return 0
}
function _rdpg__element()
{
	# 3. _element : _object
	# 4. _element : _array
	# 5. _element : _string
	# 6. _element : _number
	# 7. _element : _bool
	# 8. _element : _null

	if (_rdpg_tok_is(_TOK_LCURL()))
	{
		if (_rdpg__object())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(_TOK_LSQR()))
	{
		if (_rdpg__array())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(_TOK_STRING()))
	{
		if (_rdpg__string())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(_TOK_NUMBER()))
	{
		if (_rdpg__number())
		{
			return 1
		}
	}
	else if (_rdpg_predict(_RDPG_sym_set_2))
	{
		if (_rdpg__bool())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(_TOK_NULL()))
	{
		if (_rdpg__null())
		{
			return 1
		}
	}
	else
	{
		_rdpg_expect("set", "_element")
	}
	return 0
}
function _rdpg__object()
{
	# 9. _object : _TOK_LCURL \_prs_usr_on_obj_start _members_opt _TOK_RCURL \_prs_usr_on_obj_end

	if (_rdpg_tok_is(_TOK_LCURL()))
	{
		_prs_usr_on_obj_start()
		_rdpg_tok_next()
		if (_rdpg__members_opt())
		{
			if (_rdpg_tok_is(_TOK_RCURL()))
			{
				_prs_usr_on_obj_end()
				_rdpg_tok_next()
				return 1
			}
			else
			{
				_rdpg_expect("tok", _TOK_RCURL())
			}
		}
	}
	else
	{
		_rdpg_expect("tok", _TOK_LCURL())
	}
	return 0
}
function _rdpg__array()
{
	# 10. _array : _TOK_LSQR \_prs_usr_on_arr_start _elements_opt _TOK_RSQR \_prs_usr_on_arr_end

	if (_rdpg_tok_is(_TOK_LSQR()))
	{
		_prs_usr_on_arr_start()
		_rdpg_tok_next()
		if (_rdpg__elements_opt())
		{
			if (_rdpg_tok_is(_TOK_RSQR()))
			{
				_prs_usr_on_arr_end()
				_rdpg_tok_next()
				return 1
			}
			else
			{
				_rdpg_expect("tok", _TOK_RSQR())
			}
		}
	}
	else
	{
		_rdpg_expect("tok", _TOK_LSQR())
	}
	return 0
}
function _rdpg__string()
{
	# 11. _string : _TOK_STRING \_prs_usr_on_string

	if (_rdpg_tok_is(_TOK_STRING()))
	{
		_prs_usr_on_string()
		_rdpg_tok_next()
		return 1
	}
	else
	{
		_rdpg_expect("tok", _TOK_STRING())
	}
	return 0
}
function _rdpg__number()
{
	# 12. _number : _TOK_NUMBER \_prs_usr_on_number

	if (_rdpg_tok_is(_TOK_NUMBER()))
	{
		_prs_usr_on_number()
		_rdpg_tok_next()
		return 1
	}
	else
	{
		_rdpg_expect("tok", _TOK_NUMBER())
	}
	return 0
}
function _rdpg__bool()
{
	# 13. _bool : _TOK_TRUE \_prs_usr_on_bool
	# 14. _bool : _TOK_FALSE \_prs_usr_on_bool

	if (_rdpg_tok_is(_TOK_TRUE()))
	{
		_prs_usr_on_bool()
		_rdpg_tok_next()
		return 1
	}
	else if (_rdpg_tok_is(_TOK_FALSE()))
	{
		_prs_usr_on_bool()
		_rdpg_tok_next()
		return 1
	}
	else
	{
		_rdpg_expect("set", "_bool")
	}
	return 0
}
function _rdpg__null()
{
	# 15. _null : _TOK_NULL \_prs_usr_on_null

	if (_rdpg_tok_is(_TOK_NULL()))
	{
		_prs_usr_on_null()
		_rdpg_tok_next()
		return 1
	}
	else
	{
		_rdpg_expect("tok", _TOK_NULL())
	}
	return 0
}
function _rdpg__elements()
{
	# 16. _elements : _element _elements_rest_star

	if (_rdpg_predict(_RDPG_sym_set_1))
	{
		if (_rdpg__element())
		{
			if (_rdpg__elements_rest_star())
			{
				return 1
			}
		}
	}
	else
	{
		_rdpg_expect("set", "_elements")
	}
	return 0
}
function _rdpg__elements_opt()
{
	# 17. _elements_opt : _elements
	# 18. _elements_opt : 0

	if (_rdpg_predict(_RDPG_sym_set_1))
	{
		if (_rdpg__elements())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(_TOK_RSQR()))
	{
		return 1
	}
	else
	{
		_rdpg_expect("set", "_elements_opt")
	}
	return 0
}
function _rdpg__elements_rest()
{
	# 19. _elements_rest : _TOK_COMMA _element

	if (_rdpg_tok_match(_TOK_COMMA()))
	{
		if (_rdpg__element())
		{
			return 1
		}
	}
	else
	{
		_rdpg_expect("tok", _TOK_COMMA())
	}
	return 0
}
function _rdpg__elements_rest_star()
{
	# 20. _elements_rest_star : _elements_rest _elements_rest_star
	# 21. _elements_rest_star : 0

	while (1)
	{
		if (_rdpg_tok_is(_TOK_COMMA()))
		{
			if (_rdpg__elements_rest())
			{
				continue
			}
		}
		else if (_rdpg_tok_is(_TOK_RSQR()))
		{
			return 1
		}
		else
		{
			_rdpg_expect("set", "_elements_rest_star")
		}
		return 0
	}
}
function _rdpg__members()
{
	# 22. _members : _member _members_rest_star

	if (_rdpg_tok_is(_TOK_STRING()))
	{
		if (_rdpg__member())
		{
			if (_rdpg__members_rest_star())
			{
				return 1
			}
		}
	}
	else
	{
		_rdpg_expect("tok", _TOK_STRING())
	}
	return 0
}
function _rdpg__members_opt()
{
	# 23. _members_opt : _members
	# 24. _members_opt : 0

	if (_rdpg_tok_is(_TOK_STRING()))
	{
		if (_rdpg__members())
		{
			return 1
		}
	}
	else if (_rdpg_tok_is(_TOK_RCURL()))
	{
		return 1
	}
	else
	{
		_rdpg_expect("set", "_members_opt")
	}
	return 0
}
function _rdpg__member()
{
	# 25. _member : _TOK_STRING \_prs_usr_on_member_name _TOK_COLON _element

	if (_rdpg_tok_is(_TOK_STRING()))
	{
		_prs_usr_on_member_name()
		_rdpg_tok_next()
		if (_rdpg_tok_match(_TOK_COLON()))
		{
			if (_rdpg__element())
			{
				return 1
			}
		}
		else
		{
			_rdpg_expect("tok", _TOK_COLON())
		}
	}
	else
	{
		_rdpg_expect("tok", _TOK_STRING())
	}
	return 0
}
function _rdpg__members_rest()
{
	# 26. _members_rest : _TOK_COMMA _member

	if (_rdpg_tok_match(_TOK_COMMA()))
	{
		if (_rdpg__member())
		{
			return 1
		}
	}
	else
	{
		_rdpg_expect("tok", _TOK_COMMA())
	}
	return 0
}
function _rdpg__members_rest_star()
{
	# 27. _members_rest_star : _members_rest _members_rest_star
	# 28. _members_rest_star : 0

	while (1)
	{
		if (_rdpg_tok_is(_TOK_COMMA()))
		{
			if (_rdpg__members_rest())
			{
				continue
			}
		}
		else if (_rdpg_tok_is(_TOK_RCURL()))
		{
			return 1
		}
		else
		{
			_rdpg_expect("set", "_members_rest_star")
		}
		return 0
	}
}
# </rd>
# </parse>
# <parser_usr_implemented>
function tok_next(    _next) {
	return _lex_next()
}

function tok_err(    _arr, _len) {
	_len = rdpg_expect(_arr)

	error_print(sprintf("%s:%d:%d",
		get_file_name(),
		_lex_get_line_no(),
		_lex_get_pos()))

	error_print(sprintf("expected%s'%s', got '%s'",
				(_len > 1) ? " one of " : " ",
				_expected_str(_arr, _len),
				_lex_curr_tok()))

	pstderr(_lex_pretty_pos(_G_current_input_line))

	if (_get_fatal_error()) {
		pstderr(sprintf("%s: quitting because of -vFatalError=1",
			get_program_name()))
		exit_failure()
	}
}
function _expected_str(arr, len,    _i, _str) {
	for (_i = 1; _i <= len; ++_i) {
		_str = (_str arr[_i])
		if (_i != len)
			_str = (_str " ")
	}
	return _str
}

function _subsep(a, b) {
	if (!a) return b
	else if (!b) return a
	return (a PFT_SEP() b)
}
function _no_quotes(str) {
	gsub("\"", "", str)
	return str
}

function _full_name(name) {
	return _subsep(_get_pos(), name)
}
function _prs_init_pos() {
	vect_push(_G_position_stack, JSON_ROOT())
	vect_push(_G_input_order_keeper, JSON_ROOT())
}
function _push_pos(pos) {
	pos = _full_name(pos)
	vect_push(_G_position_stack, pos)
	vect_push(_G_input_order_keeper, pos)
}
function _get_pos() {return vect_peek(_G_position_stack)}
function _pop_pos(    _ret) {
	_ret = vect_peek(_G_position_stack)
	vect_pop(_G_position_stack)
	return _ret
}

function _add_type(type) {map_set(_G_json_type_tbl, _get_pos(), type)}
function _add_val(val) {map_set(_G_json_values_tbl, _get_pos(), val)}

function _push_jarr_ind() {vect_push(_G_array_index_stack, 0)}
function _next_arr_ind(    _ind) {
	_ind = 1 + vect_peek(_G_array_index_stack)
	vect_pop(_G_array_index_stack)
	vect_push(_G_array_index_stack, _ind)
	return _ind
}
function _pop_jarr_ind() {vect_pop(_G_array_index_stack)}

function _push_nest_obj() {vect_push(_G_nest_type_stack, JT_OBJECT())}
function _push_nest_arr() {vect_push(_G_nest_type_stack, JT_ARRAY())}
function _get_nest_type() {return vect_peek(_G_nest_type_stack)}
function _pop_nest_type(    _ret) {
	_ret = vect_peek(_G_nest_type_stack)
	vect_pop(_G_nest_type_stack)
	return _ret
}

function _handle_paths(type) {
	if (_get_nest_type() == JT_ARRAY())
		_push_pos(_next_arr_ind())
	_add_type(type)
}
function _prs_usr_on_obj_start() {
	_handle_paths(JT_OBJECT())
	_add_val(JV_OBJECT())
	_push_nest_obj()
}
function _prs_usr_on_obj_end() {
	_pop_pos()
	_pop_nest_type()
}
function _prs_usr_on_arr_start() {
	_handle_paths(JT_ARRAY())
	_add_val(JV_ARRAY())
	_push_nest_arr()
	_push_jarr_ind()
}
function _prs_usr_on_arr_end() {
	_pop_pos()
	_pop_jarr_ind()
	_pop_nest_type()
}
function _prs_usr_on_member_name() {
	_push_pos(_no_quotes(_lex_get_saved()))
}
function _prs_usr_on_string() {
	_handle_paths(JT_STRING())
	_add_val(_no_quotes(_lex_get_saved()))
	_pop_pos()
}
function _prs_usr_on_bool() {
	_handle_paths(JT_BOOL())
	_add_val(_lex_get_saved())
	_pop_pos()
}
function _prs_usr_on_number() {
	_handle_paths(JT_NUMBER())
	_add_val(_lex_get_saved())
	_pop_pos()
}
function _prs_usr_on_null() {
	_handle_paths(JT_NULL())
	_add_val(JV_NULL())
	_pop_pos()
}

function _prs_usr_init_type_set() {
	_B_awkson_type_tbl[JT_OBJECT()] = 1
	_B_awkson_type_tbl[JT_ARRAY()] = 1
	_B_awkson_type_tbl[JT_STRING()] = 1
	_B_awkson_type_tbl[JT_BOOL()] = 1
	_B_awkson_type_tbl[JT_NUMBER()] = 1
	_B_awkson_type_tbl[JT_NULL()] = 1

	_B_awkson_type_default_val[JT_OBJECT()] = JV_OBJECT()
	_B_awkson_type_default_val[JT_ARRAY()] = JV_ARRAY()
	_B_awkson_type_default_val[JT_STRING()] = ""
	_B_awkson_type_default_val[JT_BOOL()] = _TOK_FALSE()
	_B_awkson_type_default_val[JT_NUMBER()] = 0
	_B_awkson_type_default_val[JT_NULL()] = _TOK_NULL()
}
function _prs_usr_type_set_has(type) {
	return (type in _B_awkson_type_tbl)
}
function _prs_usr_type_get_default_val(type) {
	return _B_awkson_type_default_val[type]
}
# </parser_usr_implemented>
